### PR TITLE
Nix init

### PR DESCRIPTION
**Pull request by Eveeifyeve**
Adds nix devshell to skeditor for an nix/nixos user that wants contribute to skeditor. I am also making a pr that adds the package to nixpkgs [here](https://github.com/NixOS/nixpkgs/pull/351582).
Unfortunately it requires everyone to use flakes which is an [experimental feature](https://nix.dev/concepts/flakes) but I have no idea how to make a `shell.nix`.

### CODE REVIEW

**Comment by Eveeifyeve** [comment]
Eventually I will make something for dependabot or renovate, but for now the best to use to update flakes is the [update-flake-lock github action](https://github.com/DeterminateSystems/update-flake-lock)

**Comment by Eveeifyeve** [comment]
CC @NotroDev

**Comment by NotroDev** [comment]
thanks

**Comment by NotroDev** [comment]
@Eveeifyeve is it normal the update-flake-lock workflow fails?
I tried to fix it with no success. I don't want to break it because tbh I have absolutely no knowledge about nix

**Comment by Eveeifyeve** [comment]
> @Eveeifyeve is it normal the update-flake-lock workflow fails? I tried to fix it with no success. I don't want to break it because tbh I have absolutely no knowledge about nix

It's not normal for it to fail I will take a look at it.

**Comment by Eveeifyeve** [comment]
@NotroDev, Please make sure you enabled this setting under settings -> Actions -> General -> Scroll down you should find this setting turn it on or the workflow will not work.

image

**Comment by NotroDev** [comment]
@Eveeifyeve thanks, I think it works now :)
https://github.com/SkEditorTeam/SkEditor/pull/129

**Pull request merged**
